### ISSUE TITLE
2nd Movie Night - Fall, 2018

### ISSUE THREAD

**Issue by Abhi-wan-kenobhi** [trusuanimeclub/Planning#15]
### **Here's a bunch of movies I picked and we can narrow it down to either 3 or 5 so we can generate a poll for people.**
---
1. **Girls & Panzer movie** (cute, slice of life - [MAL](https://myanimelist.net/anime/18617/Girls___Panzer_Movie))

2. ~~**Sayonara no Asa ni Yakusoku no Hana wo Kazarou** (Apparently a new one. We can test this one out by watching it ourselves first. Drama, Fantasy - [MAL](https://myanimelist.net/anime/35851/Sayonara_no_Asa_ni_Yakusoku_no_Hana_wo_Kazarou))~~

3. **Toki wo Kakeru Shoujo** (Sci-fi and a bit of drama and adventure. It's decently famous and a pretty good one. - [MAL](https://myanimelist.net/anime/2236/Toki_wo_Kakeru_Shoujo))

4. ~~**Kotonoha no Niwa** (Drama, Romantic and a bit of a sad one. - [MAL](https://myanimelist.net/anime/16782/Kotonoha_no_Niwa))~~

5. ~~**Summer Wars** (It's hard to describe this one. A bit of a sci-fi but a fun watch. - [MAL](https://myanimelist.net/anime/5681/Summer_Wars))~~

6. ~~**Sakasama no Patema** (Sci-fi. Haven't watched it myself but I've been told it's good. - [MAL](https://myanimelist.net/anime/12477/Sakasama_no_Patema))~~

7. **Ookami Kodomo no Ame to Yuki** (Fantasy and a bit of a sad slice of life - [MAL](https://myanimelist.net/anime/12355/Ookami_Kodomo_no_Ame_to_Yuki))

8. **Ansatsu Kyoushitsu: 365-nichi no Jikan** (Big on comedy and action. - [MAL](https://myanimelist.net/anime/33513/Ansatsu_Kyoushitsu__365-nichi_no_Jikan))

9. **Paprika** (Dark and psychological - [MAL](https://myanimelist.net/anime/1943/Paprika))
---
I tried to kinda pull good movies from all genres so we can narrow them down to at least 1 from each genre.
Looking for input from ya'll to narrow it down! <3

---

#### Task Checklist

- [x] Narrow down the list and make a poll

- [x] Collect data from poll and decide the date (it's probably gonna be 26th Oct if we're doing the movie monthly)

- [x] Book CT 200

- [ ] Book the place for the banner

- [ ] Design banner

- [x] Design poster

- [ ] Post the event on our FB page

- [ ] Get the banner and posters printed

- [ ] Hang the banner and posters

**Comment by napcolors** [comment]
**Recommendations from paper survey**
-Koe no Katachi [2votes]
-Howl's Moving Castle
-Princess Mononoke
-Laputa: Castle in the Sky
-No Game No Life: Zero, 
-Your Name
-Planeterian: Man of the Stars
-Fate Stay Night Heaven Feels pt 1
-Jin Roh
-Red line
-K-on Movie
-Mind Game
-Night is Short
-Walk on Girl
-Summer Wars
-Cowboy Bebop
-Gantz
-Escaflowne
-Darling in the Franxx
-Persona 5
-Meitantei Conan
-DBZ
-SAO
-Saint Seinya
-Deathnote
-Japanese movies(ft. japanese actors/actresses)
-Studio Ghibli
-Missaki films
-indie productions
