### ISSUE TITLE
3rd Movie Night - Fall, 2018

### ISSUE THREAD

**Issue by Abhi-wan-kenobhi** [trusuanimeclub/Planning#18]
### **Here's a bunch of movies I picked for the next movie night on Nov 30th.**

---

1. **K-On! movie** (Cute, slice of life. - [MAL](https://myanimelist.net/anime/9617/K-On_Movie))

2. **Koe no Katachi** (Ya'll already know what this is. Drama, Romance - [MAL](https://myanimelist.net/anime/28851/Koe_no_Katachi))

3. **Gintama Movie 1: Shinyaku Benizakura-hen** (Comedy, parody. - [MAL](https://myanimelist.net/anime/7472/Gintama_Movie_1__Shinyaku_Benizakura-hen))

4. **Bakemono no Ko** (Adventure, supernatural, wholesome. - [MAL](https://myanimelist.net/anime/28805/Bakemono_no_Ko))

5. **No Game No Life: Zero** (Fantasy, comedy, supernatural. - [MAL](https://myanimelist.net/anime/33674/No_Game_No_Life__Zero))

---

#### Task Checklist

- [x] Make a poll

- [ ] Post the event on our FB page

- [ ] Announce on Discord

- [ ] Get the banner and posters printed

- [ ] Hang the banner and posters

Tylor:
- [x] Book CT 200
- [x] Book the place for the banner
- [ ] Apply for grant
- [ ] Design banner
- [ ] Design poster
- [ ] Purchase Blu-Ray from Sentai Filmworks
- [ ] Coordinate with Sentai with licensing
- [ ] Send email
- [ ] Update website

**Comment by frogcrush** [comment]
No Game, No Life: Zero was chosen as the movie.
